from typing import Any

def parse_version(v: Any): ...
def sqlalchemy_version(op: Any, val: Any): ...
def engine_config_warning(config: Any, version: Any, deprecated_config_key: Any, engine_option: Any) -> None: ...
